name: Linting component

on:
  workflow_call:
    inputs:
      TIMEOUT:
        required: false
        type: number
        default: 10

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.TIMEOUT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Setup npm user
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - run: npm ci
      - run: npm run lint
